#!/bin/sh /etc/rc.common
# Copyright (C) 2026 NanoPi-R2S
# shellcheck disable=SC2034  # USE_PROCD/START/STOP read by /etc/rc.common at runtime
USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/fan-pid-loop

start_service() {
    # shellcheck disable=SC3043  # 'local' is supported in OpenWRT's busybox ash
    local enabled
    config_load 'fan'
    config_get enabled pid enabled '0'

    if [ "$enabled" != "1" ]; then
        echo "fan-pid disabled in /etc/config/fan; not starting"
        return 0
    fi

    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "fan"
}
